training_article_homepage:
    pattern:  /
    defaults: { _controller: TrainingArticleBundle:Default:index }
    
training_article_ajouter:
    pattern:  /ajouter
    defaults: { _controller: TrainingArticleBundle:Default:ajouter }

training_article_afficher:
    pattern:  /{id}/afficher
    defaults: { _controller: TrainingArticleBundle:Default:afficher }
    requirements :
      id : \d+
      
training_article_editer:
    pattern:  /{id}/editer
    defaults: { _controller: TrainingArticleBundle:Default:editer }
    requirements :
      id : \d+
      
training_article_supprimer:
    pattern:  /{id}/supprimer
    defaults: { _controller: TrainingArticleBundle:Default:supprimer }
    requirements :
      id : \d+