training_article_homepage:
    pattern:  /
    defaults: { _controller: TrainingArticleBundle:Default:index }
    
training_article_ajouter:
    pattern:  /ajouter
    defaults: { _controller: TrainingArticleBundle:Default:ajouter }
